// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0WsLD2KL_CrvuMrCfb3hUuO_mrrQHtRw',
    appId: '1:1021807251081:web:1d66366436b9c0dd7a0058',
    messagingSenderId: '1021807251081',
    projectId: 'tryagain-b1c44',
    authDomain: 'tryagain-b1c44.firebaseapp.com',
    storageBucket: 'tryagain-b1c44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xL-YZTKwa_mSkkKL4fHMGb_gIJGqjGE',
    appId: '1:1021807251081:android:ea2180e90fb9c2107a0058',
    messagingSenderId: '1021807251081',
    projectId: 'tryagain-b1c44',
    storageBucket: 'tryagain-b1c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1pdnVgs7kEYQRivOawUgpmwipXxAYOQ',
    appId: '1:1021807251081:ios:0d597db6185b261c7a0058',
    messagingSenderId: '1021807251081',
    projectId: 'tryagain-b1c44',
    storageBucket: 'tryagain-b1c44.appspot.com',
    iosBundleId: 'com.example.tryagain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1pdnVgs7kEYQRivOawUgpmwipXxAYOQ',
    appId: '1:1021807251081:ios:cb5491b6aeb3992b7a0058',
    messagingSenderId: '1021807251081',
    projectId: 'tryagain-b1c44',
    storageBucket: 'tryagain-b1c44.appspot.com',
    iosBundleId: 'com.example.tryagain.RunnerTests',
  );
}
